
  # Position Controllers ---------------------------------------
  # joint1_position_controller:

type: position_controllers/JointPositionController  #working 1
# type: effort_controllers/JointPositionController     #working 2

joint: base_piston_moving
# pid: {p: 300.0, i: 100.01, d: 10.0}
#pid: {p: 2000.0, i: 100, d: 500.0}
pid: {p: 20.0, i: 5, d: 5.0}

has_position_limits: true
min_position: 0.0
#max_position: 1.0
max_position: 0.2
has_velocity_limits: true
#max_velocity: 0.01
max_velocity: 0.5
has_acceleration_limits: true
#max_acceleration: 0.01
max_acceleration: 0.1
has_jerk_limits: true
max_jerk: 0.01
has_effort_limits: true
max_effort: 100.0